---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */
role_name_check: 1

dependency:
  name: 'galaxy'

driver:
  name: 'docker'

platforms:
- name: 'instance'
  image: 'geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest'
  volumes:
  - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
  cgroupns_mode: 'host'
  privileged: true
  pre_build_image: true

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: 'ansible'
  playbooks:
    converge: 'converge.yml'
